language: android

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - tools
    - build-tools-28.0.2
    - android-28
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet
    - pip install --user awscli

before_install:
        - chmod +x gradlew
script:
  - ./gradlew check