language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet
    - pip install --user awscli

before_install:
        - chmod +x gradlew
script:
  - ./gradlew check